### ISSUE TITLE
Daemon not running - start monero daemon when it has been succesfully started

### ISSUE THREAD

**Issue by iperrealistico** [everoddandeven/monerod-gui#12]
### Steps to reproduce

1. Set the monderod.exe file in the settings
2. Import config (successful this time)
3. Start monerod using the button in the gui
4. Got a notification about it getting started
5. Got a notification of monerod being succesfully started
6. Can confirm monerod is started from the log tab in the gui and from p2pool executable that resumed working
7. **Every tab that is not the logs tab says monerod has not been started** (dash, blockchain, transaction ... and so on)
8. I randomly received a "prevented unsafe content" error

![Image](https://github.com/user-attachments/assets/b525937a-454e-4669-b515-1fb225cf8b0d)
![Image](https://github.com/user-attachments/assets/14b696a4-3a06-4ad8-a576-535c586ec46d)

### ✔️ Expected Behavior

The gui should be able to see monerod running and show content relative to the tab I clicked on

### 🔍 Additional context

Windows
Randomly popped up a prevented unsafe content in appdata directory (never seen this before)

**Comment by everoddandeven** [comment]
Hi @iperrealistico ,that warning is a security check I put in, which prevents monerod-gui from opening any resources it shouldn't, like external remote pages. Could you please attach the configuration you used? Are you using the latest version of monerod? Thank you for reporting this issue.

**Comment by iperrealistico** [comment]
Monerod 0.18.3.4-release
Config: https://pastebin.com/5e5TMtAg

Why the hell should the GUI open external pages? And why did it even try 😵‍💫

**Comment by everoddandeven** [comment]
@iperrealistico are you using standalone app or installer? Are you on Windows 11?

**Comment by everoddandeven** [comment]
@iperrealistico could you test the executables you find in the artifacts of my latest build? 
I was unable to reproduce the error, but I fixed a few things that might have caused this strange behavior.

https://github.com/everoddandeven/monerod-gui/actions/runs/13144605952

**Comment by iperrealistico** [comment]
nope, problem persists, logs start showing, monero daemon is started as shown by the notification but the gui says daemon not running, start monero

windows 11
portable
